# Generated by Django 2.1.7 on 2019-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190425_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stream_link',
            field=models.TextField(default='no-link'),
        ),
    ]
